### Well- or de-differentiated liposarcoma {#resultsPcaWellOrDeDifferentiatedLiposarcoma}

#### On most genes {#resultsPcaWellOrDeDifferentiatedLiposarcomaOnMostGenes}

```{r resultsPcaWellOrDeDifferentiatedLiposarcomaOnMostGenes}
source("loadEnv.R")
smi <- "out/r/annotate_tcga/vsd.rds"
linkSmiToRmdAndBookDir(smi)
vsd <- readRDS(smi)

vsd <- vsd[
  ,
  colData(vsd)$primary_diagnosis %in% c(
    "Dedifferentiated liposarcoma",
    "Liposarcoma, well differentiated"
  )
]

sd_threshold <- 0.3
vsd <- vsd[
  apply(
    assay(vsd),
    1,
    sd
  ) > sd_threshold
]

rna_samples_metadata <- droplevels(colData(vsd))

d_pca <- prcomp(
  t(assay(vsd)),
  scale = TRUE
)
```

In this section, most genes are kept for the PCA. Only those with a standard deviation lower than 0.3 are removed, leading to a dataset with `r nrow(vsd)` genes.

```{r resultsPcaWellOrDeDifferentiatedLiposarcomaOnMostGenesDefinePlotPcaRnaSeqIndWithMainCovariates}
fig_height_pca <- 8
fig_width_pca <- 10
plotPcaRnaSeqIndWithMainCovariates <- function(
                                               d = d_pca,
                                               d_metadata = rna_samples_metadata,
                                               axes_to_plot = c(1, 2)) {
  p1 <- fviz_pca_ind(
    d,
    axes = axes_to_plot,
    mean.point = FALSE,
    label = "none",
    col.ind = d_metadata$age_at_index
  )
  p1 <- p1 + scale_color_continuous(name = "Age at index")
  p1 <- p1 + ggtitle(NULL)
  p1 <- p1 + theme(legend.position = "bottom")
  p1 <- p1 + guides(
    color = guide_legend(
      title.position = "top",
      # hjust = 0.5 centres the title horizontally
      title.hjust = 0.5,
      label.position = "bottom"
    )
  )

  p2 <- fviz_pca_ind(
    d,
    axes = axes_to_plot,
    mean.point = FALSE,
    label = "none",
    habillage = d_metadata$primary_diagnosis,
    legend.title = "primary_diagnosis"
  )
  p2 <- p2 + ggtitle(NULL)
  p2 <- p2 + theme(legend.position = "bottom")
  p2 <- p2 + guides(
    color = guide_legend(
      title.position = "top",
      # hjust = 0.5 centres the title horizontally
      title.hjust = 0.5,
      label.position = "bottom"
    )
  )

  p3 <- fviz_pca_ind(
    d,
    axes = axes_to_plot,
    mean.point = FALSE,
    label = "none",
    col.ind = d_metadata$paper_OS_days,
  )
  p3 <- p3 + scale_color_continuous(name = "paper_OS_days")
  p3 <- p3 + ggtitle(NULL)
  p3 <- p3 + theme(legend.position = "bottom")
  p3 <- p3 + guides(
    color = guide_legend(
      title.position = "top",
      # hjust = 0.5 centres the title horizontally
      title.hjust = 0.5,
      label.position = "bottom"
    )
  )

  p4 <- fviz_pca_ind(
    d,
    axes = axes_to_plot,
    mean.point = FALSE,
    label = "none",
    habillage = d_metadata$paper_DSS_status,
    legend.title = "paper_DSS_status"
  )
  p4 <- p4 + ggtitle(NULL)
  p4 <- p4 + theme(legend.position = "bottom")
  p4 <- p4 + guides(
    color = guide_legend(
      title.position = "top",
      # hjust = 0.5 centres the title horizontally
      title.hjust = 0.5,
      label.position = "bottom"
    )
  )

  p5 <- fviz_pca_ind(
    d,
    axes = axes_to_plot,
    mean.point = FALSE,
    label = "none",
    habillage = d_metadata$paper_OS_status,
    legend.title = "paper_OS_status"
  )
  p5 <- p5 + ggtitle(NULL)
  p5 <- p5 + theme(legend.position = "bottom")
  p5 <- p5 + guides(
    color = guide_legend(
      title.position = "top",
      # hjust = 0.5 centres the title horizontally
      title.hjust = 0.5,
      label.position = "bottom"
    )
  )

  p6 <- fviz_pca_ind(
    d,
    axes = axes_to_plot,
    mean.point = FALSE,
    label = "none",
    habillage = d_metadata$paper_tumor_status,
    legend.title = "paper_tumor_status"
  )
  p6 <- p6 + ggtitle(NULL)
  p6 <- p6 + theme(legend.position = "bottom")
  p6 <- p6 + guides(
    color = guide_legend(
      title.position = "top",
      # hjust = 0.5 centres the title horizontally
      title.hjust = 0.5,
      label.position = "bottom"
    )
  )


  ggarrange(
    p1,
    p2,
    p3,
    p4,
    p5,
    p6,
    ncol = 3,
    nrow = 2,
    align = "h"
  )
}
```

```{r resultsPcaWellOrDeDifferentiatedLiposarcomaOnMostGenesIndPC1And2, fig.height=fig_height_pca, fig.width=fig_width_pca, fig.cap="PCA Individuals, components 1 and 2"}
plotPcaRnaSeqIndWithMainCovariates()
```

```{r resultsPcaWellOrDeDifferentiatedLiposarcomaOnMostGenesIndPC3And4, fig.height=fig_height_pca, fig.width=fig_width_pca, fig.cap="PCA Individuals, components 3 and 4"}
plotPcaRnaSeqIndWithMainCovariates(axes_to_plot = c(3, 4))
```

```{r resultsPcaWellOrDeDifferentiatedLiposarcomaOnMostGenesIndPC5And6, fig.height=fig_height_pca, fig.width=fig_width_pca, fig.cap="PCA Individuals, components 5 and 6"}
plotPcaRnaSeqIndWithMainCovariates(axes_to_plot = c(5, 6))
```

```{r resultsPcaWellOrDeDifferentiatedLiposarcomaOnMostGenesIndPC7And8, fig.height=fig_height_pca, fig.width=fig_width_pca, fig.cap="PCA Individuals, components 7 and 8"}
plotPcaRnaSeqIndWithMainCovariates(axes_to_plot = c(7, 8))
```

```{r resultsPcaWellOrDeDifferentiatedLiposarcomaOnMostGenesIndPC9And10, fig.height=fig_height_pca, fig.width=fig_width_pca, fig.cap="PCA Individuals, components 9 and 10"}
plotPcaRnaSeqIndWithMainCovariates(axes_to_plot = c(9, 10))
```
